import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import SmoothScrollWrapper from "@/components/SmoothScrollWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScrollWrapper>
          <Header />
          <main className="relative min-h-screen w-screen overflow-x-hidden">
            {children}
          </main>
        </SmoothScrollWrapper>
      </body>
    </html>
  );
}
